### ISSUE TITLE
Trigger hand tool instead of writing a blank character

### ISSUE THREAD

**Issue by oscardoso** [icons8/lunacy-docs#76]
**OS:** pop!_os 22.04 LTS
**LUNACY VERSION:** 9.1.0
**package:** flatpak

**ISSUE:** When I try to change or write a new text and I press the space key to enter a new blank space this does not happen, the hand tool appears instead.

I also installed the **deb package** and it has the same problem.

**Comment by IvanTheNiceMan** [comment]
I have checked the official Icons8 lunacy documentation page for possible solutions, and the closest that i was able to find is "layers and images on the canvas stretching and flickering when I scroll and zoom". I installed all the newest drivers/updates possible, but that didnt work at all.

**Comment by Mikolaytis** [comment]
This is not our bug tracker. Here we accept only documentation-related issues.
Please, report new bugs here: https://community.icons8.com/c/lunacy/7

About issue - I hope it fixed in the recent updates. If not - contact as via community forum. Thanks!
Also about flatpack - we are not investing resources into it. Now we are focused only on ubuntu support. Maybe when our team will enlarge when we will be profitable - we will work on it. Sorry for that.
