### ISSUE TITLE
Error opening Lunacy Sketch file

### ISSUE THREAD

**Issue by anton78bon** [icons8/lunacy-docs#78]
Hello, 

Just now when I try to close Lunacy from the file I worked on, it crashed. When I try to re-open the file, it said :

**Can't open file : wrong format or an internal error**

Can anyone please help me, how to fix this corrupt file, or I have to re-work it all from beginning

[ExecutiveSummary.zip](https://github.com/icons8/lunacy-docs/files/13327511/ExecutiveSummary.zip)

**Comment by Mikolaytis** [comment]
This is not our bug tracker. Here we accept only documentation-related issues.
Please, report new bugs here: https://community.icons8.com/c/lunacy/7

About issue - I hope it fixed in the recent updates. If not - contact as via community forum. Thanks!
To fix your file you can contact our support via Lunacy app directly - usually they can restore a file.
